<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ds0a245pi/image/upload/v1554361302/18ROKm6G_400x400.jpg" alt="Chibike">
                        <h6>Chibike Nwankwo</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/nwankwo_chibike" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/nstandev" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@nwankwo.stanislaus/" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                            An enthusiastic budding software developer familiar with PHP, Javascript, Java(for android) and Python. Currently working with Laravel, Django and React frameworks.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
